/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.0.6.0 (NJsonSchema v10.0.23.0 (Newtonsoft.Json v11.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming

import { mergeMap as _observableMergeMap, catchError as _observableCatch } from 'rxjs/operators';
import { Observable, throwError as _observableThrow, of as _observableOf } from 'rxjs';
import { Injectable, Inject, Optional, InjectionToken } from '@angular/core';
import { HttpClient, HttpHeaders, HttpResponse, HttpResponseBase } from '@angular/common/http';

export const BASE_URL = new InjectionToken<string>('BASE_URL');

@Injectable()
export class IncidentsClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ? baseUrl : "";
    }

    getAll(limit: number | null, offset: number | null): Observable<IncidentListDto | null> {
        let url_ = this.baseUrl + "/api/incidents?";
        if (limit === undefined)
            throw new Error("The parameter 'limit' must be defined.");
        else
            url_ += "limit=" + encodeURIComponent("" + limit) + "&"; 
        if (offset === undefined)
            throw new Error("The parameter 'offset' must be defined.");
        else
            url_ += "offset=" + encodeURIComponent("" + offset) + "&"; 
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetAll(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetAll(<any>response_);
                } catch (e) {
                    return <Observable<IncidentListDto | null>><any>_observableThrow(e);
                }
            } else
                return <Observable<IncidentListDto | null>><any>_observableThrow(response_);
        }));
    }

    protected processGetAll(response: HttpResponseBase): Observable<IncidentListDto | null> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 ? IncidentListDto.fromJS(resultData200) : <any>null;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<IncidentListDto | null>(<any>null);
    }

    create(type: IncidentTypeDto, detected: Date, reporter: string | null, description: string | null | undefined, tlp: IncidentTlp): Observable<ObjectId | null> {
        let url_ = this.baseUrl + "/api/incidents?";
        if (type === undefined || type === null)
            throw new Error("The parameter 'type' must be defined and cannot be null.");
        else
            url_ += "Type=" + encodeURIComponent("" + type) + "&"; 
        if (detected === undefined || detected === null)
            throw new Error("The parameter 'detected' must be defined and cannot be null.");
        else
            url_ += "Detected=" + encodeURIComponent(detected ? "" + detected.toJSON() : "") + "&"; 
        if (reporter === undefined)
            throw new Error("The parameter 'reporter' must be defined.");
        else
            url_ += "Reporter=" + encodeURIComponent("" + reporter) + "&"; 
        if (description !== undefined)
            url_ += "Description=" + encodeURIComponent("" + description) + "&"; 
        if (tlp === undefined || tlp === null)
            throw new Error("The parameter 'tlp' must be defined and cannot be null.");
        else
            url_ += "Tlp=" + encodeURIComponent("" + tlp) + "&"; 
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processCreate(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processCreate(<any>response_);
                } catch (e) {
                    return <Observable<ObjectId | null>><any>_observableThrow(e);
                }
            } else
                return <Observable<ObjectId | null>><any>_observableThrow(response_);
        }));
    }

    protected processCreate(response: HttpResponseBase): Observable<ObjectId | null> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 ? ObjectId.fromJS(resultData200) : <any>null;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<ObjectId | null>(<any>null);
    }

    get(id: string): Observable<IncidentDto | null> {
        let url_ = this.baseUrl + "/api/incidents/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id)); 
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGet(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGet(<any>response_);
                } catch (e) {
                    return <Observable<IncidentDto | null>><any>_observableThrow(e);
                }
            } else
                return <Observable<IncidentDto | null>><any>_observableThrow(response_);
        }));
    }

    protected processGet(response: HttpResponseBase): Observable<IncidentDto | null> {
        const status = response.status;
        const responseBlob = 
            response instanceof HttpResponse ? response.body : 
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }};
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 ? IncidentDto.fromJS(resultData200) : <any>null;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<IncidentDto | null>(<any>null);
    }
}

export class IncidentListDto implements IIncidentListDto {
    total?: number | undefined;
    items?: IncidentListItemDto[] | undefined;

    constructor(data?: IIncidentListDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.total = data["Total"];
            if (Array.isArray(data["Items"])) {
                this.items = [] as any;
                for (let item of data["Items"])
                    this.items!.push(IncidentListItemDto.fromJS(item));
            }
        }
    }

    static fromJS(data: any): IncidentListDto {
        data = typeof data === 'object' ? data : {};
        let result = new IncidentListDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Total"] = this.total;
        if (Array.isArray(this.items)) {
            data["Items"] = [];
            for (let item of this.items)
                data["Items"].push(item.toJSON());
        }
        return data; 
    }
}

export interface IIncidentListDto {
    total?: number | undefined;
    items?: IncidentListItemDto[] | undefined;
}

export class IncidentListItemDto implements IIncidentListItemDto {
    id!: string;
    type!: IncidentTypeDto;
    modified!: Date;
    created!: Date;
    reporter!: string;

    constructor(data?: IIncidentListItemDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.id = data["Id"];
            this.type = data["Type"];
            this.modified = data["Modified"] ? new Date(data["Modified"].toString()) : <any>undefined;
            this.created = data["Created"] ? new Date(data["Created"].toString()) : <any>undefined;
            this.reporter = data["Reporter"];
        }
    }

    static fromJS(data: any): IncidentListItemDto {
        data = typeof data === 'object' ? data : {};
        let result = new IncidentListItemDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Id"] = this.id;
        data["Type"] = this.type;
        data["Modified"] = this.modified ? this.modified.toISOString() : <any>undefined;
        data["Created"] = this.created ? this.created.toISOString() : <any>undefined;
        data["Reporter"] = this.reporter;
        return data; 
    }
}

export interface IIncidentListItemDto {
    id: string;
    type: IncidentTypeDto;
    modified: Date;
    created: Date;
    reporter: string;
}

export enum IncidentTypeDto {
    None = "None",
    Malware = "Malware",
    Phishing = "Phishing",
    SocialEngineering = "SocialEngineering",
    Ddos = "Ddos",
}

export class ObjectId implements IObjectId {
    id!: string;

    constructor(data?: IObjectId) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.id = data["Id"];
        }
    }

    static fromJS(data: any): ObjectId {
        data = typeof data === 'object' ? data : {};
        let result = new ObjectId();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Id"] = this.id;
        return data; 
    }
}

export interface IObjectId {
    id: string;
}

export enum IncidentTlp {
    Red = "Red",
    Yellow = "Yellow",
    Green = "Green",
    White = "White",
}

export class IncidentDto implements IIncidentDto {
    id!: string;
    type!: IncidentTypeDto;
    detected!: Date;
    created!: Date;
    reporter?: string | undefined;
    description?: string | undefined;
    tlp!: IncidentTlp;

    constructor(data?: IIncidentDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.id = data["Id"];
            this.type = data["Type"];
            this.detected = data["Detected"] ? new Date(data["Detected"].toString()) : <any>undefined;
            this.created = data["Created"] ? new Date(data["Created"].toString()) : <any>undefined;
            this.reporter = data["Reporter"];
            this.description = data["Description"];
            this.tlp = data["Tlp"];
        }
    }

    static fromJS(data: any): IncidentDto {
        data = typeof data === 'object' ? data : {};
        let result = new IncidentDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Id"] = this.id;
        data["Type"] = this.type;
        data["Detected"] = this.detected ? this.detected.toISOString() : <any>undefined;
        data["Created"] = this.created ? this.created.toISOString() : <any>undefined;
        data["Reporter"] = this.reporter;
        data["Description"] = this.description;
        data["Tlp"] = this.tlp;
        return data; 
    }
}

export interface IIncidentDto {
    id: string;
    type: IncidentTypeDto;
    detected: Date;
    created: Date;
    reporter?: string | undefined;
    description?: string | undefined;
    tlp: IncidentTlp;
}

export class SwaggerException extends Error {
    message: string;
    status: number; 
    response: string; 
    headers: { [key: string]: any; };
    result: any; 

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isSwaggerException = true;

    static isSwaggerException(obj: any): obj is SwaggerException {
        return obj.isSwaggerException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): Observable<any> {
    if (result !== null && result !== undefined)
        return _observableThrow(result);
    else
        return _observableThrow(new SwaggerException(message, status, response, headers, null));
}

function blobToText(blob: any): Observable<string> {
    return new Observable<string>((observer: any) => {
        if (!blob) {
            observer.next("");
            observer.complete();
        } else {
            let reader = new FileReader(); 
            reader.onload = event => { 
                observer.next((<any>event.target).result);
                observer.complete();
            };
            reader.readAsText(blob); 
        }
    });
}